var annotated_dup =
[
    [ "ev", null, [
      [ "Mat", null, [
        [ "Mat_", "classev_1_1Mat_1_1Mat__.html", "classev_1_1Mat_1_1Mat__" ],
        [ "Binary_", "classev_1_1Mat_1_1Binary__.html", "classev_1_1Mat_1_1Binary__" ],
        [ "Ternary_", "classev_1_1Mat_1_1Ternary__.html", "classev_1_1Mat_1_1Ternary__" ],
        [ "Time", "classev_1_1Mat_1_1Time.html", "classev_1_1Mat_1_1Time" ],
        [ "Polarity", "classev_1_1Mat_1_1Polarity.html", "classev_1_1Mat_1_1Polarity" ],
        [ "Counter", "classev_1_1Mat_1_1Counter.html", "classev_1_1Mat_1_1Counter" ]
      ] ],
      [ "Event_", "classev_1_1Event__.html", "classev_1_1Event__" ],
      [ "efft", "classev_1_1efft.html", null ],
      [ "Array_", "classev_1_1Array__.html", "classev_1_1Array__" ],
      [ "CircularBuffer_", "classev_1_1CircularBuffer__.html", "classev_1_1CircularBuffer__" ],
      [ "Deque_", "classev_1_1Deque__.html", "classev_1_1Deque__" ],
      [ "PersistentQueue_", "classev_1_1PersistentQueue__.html", "classev_1_1PersistentQueue__" ],
      [ "Queue_", "classev_1_1Queue__.html", "classev_1_1Queue__" ],
      [ "SlidingWindow_", "classev_1_1SlidingWindow__.html", "classev_1_1SlidingWindow__" ],
      [ "Vector_", "classev_1_1Vector__.html", "classev_1_1Vector__" ],
      [ "AugmentedEvent_", "classev_1_1AugmentedEvent__.html", "classev_1_1AugmentedEvent__" ],
      [ "Size3_", "classev_1_1Size3__.html", "classev_1_1Size3__" ],
      [ "Rect3_", "classev_1_1Rect3__.html", "classev_1_1Rect3__" ],
      [ "Circ_", "structev_1_1Circ__.html", "structev_1_1Circ__" ],
      [ "BiasValue", "structev_1_1BiasValue.html", null ],
      [ "StampedMat", "classev_1_1StampedMat.html", null ],
      [ "xyz_t", "structev_1_1xyz__t.html", null ],
      [ "Imu", "structev_1_1Imu.html", null ],
      [ "AbstractCamera", "classev_1_1AbstractCamera.html", "classev_1_1AbstractCamera" ],
      [ "Davis", "classev_1_1Davis.html", "classev_1_1Davis" ],
      [ "UndistortMap", "classev_1_1UndistortMap.html", null ],
      [ "AbstractReader_", "classev_1_1AbstractReader__.html", "classev_1_1AbstractReader__" ],
      [ "HDF5Reader", "classev_1_1HDF5Reader.html", null ],
      [ "PlainTextReader", "classev_1_1PlainTextReader.html", null ],
      [ "AbstractRepresentation_", "classev_1_1AbstractRepresentation__.html", "classev_1_1AbstractRepresentation__" ],
      [ "EventHistogram_", "classev_1_1EventHistogram__.html", "classev_1_1EventHistogram__" ],
      [ "EventImage_", "classev_1_1EventImage__.html", null ],
      [ "PointCloud_", "classev_1_1PointCloud__.html", "classev_1_1PointCloud__" ],
      [ "TimeSurface_", "classev_1_1TimeSurface__.html", "classev_1_1TimeSurface__" ]
    ] ],
    [ "caer_device_handle", "structcaer__device__handle.html", null ],
    [ "ContainerTestFixture", "classContainerTestFixture.html", null ],
    [ "HDF5ReaderTest", "classHDF5ReaderTest.html", null ],
    [ "PlainTextReaderTest", "classPlainTextReaderTest.html", null ],
    [ "SlidingWindowTest", "classSlidingWindowTest.html", null ]
];