/*!
\file options.hpp
\brief OpenEV compilation options.
\author Raul Tapia
*/
#ifndef OPTIONS_HPP
#define OPTIONS_HPP

#define OE_IS_ENABLED_MODULE_ALGORITHMS 1
#define OE_IS_ENABLED_MODULE_CONTAINERS 1
#define OE_IS_ENABLED_MODULE_CORE 1
#define OE_IS_ENABLED_MODULE_DEVICES 1
#define OE_IS_ENABLED_MODULE_EVPROC 1
#define OE_IS_ENABLED_MODULE_READERS 1
#define OE_IS_ENABLED_MODULE_REPRESENTATIONS 1

#endif // OPTIONS_HPP
