/*!
\file options.hpp
\brief OpenEV compilation options.
\author Raul Tapia
*/
#ifndef OPTIONS_HPP
#define OPTIONS_HPP

#define OE_HAVE_VIZ @HAVE_VIZ@

#define OE_HAVE_MODULE_ALGORITHM @HAVE_MODULE_ALGORITHM@
#define OE_HAVE_MODULE_CONTAINERS @HAVE_MODULE_CONTAINERS@
#define OE_HAVE_MODULE_CORE @HAVE_MODULE_CORE@
#define OE_HAVE_MODULE_DEVICES @HAVE_MODULE_DEVICES@
#define OE_HAVE_MODULE_READERS @HAVE_MODULE_READERS@
#define OE_HAVE_MODULE_REPRESENTATIONS @HAVE_MODULE_REPRESENTATIONS@
#define OE_HAVE_MODULE_UTILS @HAVE_MODULE_UTILS@

#endif // OPTIONS_HPP
