/*!
\file options.hpp
\brief OpenEV compilation options.
\author Raul Tapia
*/
#ifndef OPTIONS_HPP
#define OPTIONS_HPP

#define OE_IS_ENABLED_MODULE_ALGORITHMS @IS_ENABLED_MODULE_ALGORITHMS@
#define OE_IS_ENABLED_MODULE_CONTAINERS @IS_ENABLED_MODULE_CONTAINERS@
#define OE_IS_ENABLED_MODULE_CORE @IS_ENABLED_MODULE_CORE@
#define OE_IS_ENABLED_MODULE_DEVICES @IS_ENABLED_MODULE_DEVICES@
#define OE_IS_ENABLED_MODULE_EVPROC @IS_ENABLED_MODULE_EVPROC@
#define OE_IS_ENABLED_MODULE_READERS @IS_ENABLED_MODULE_READERS@
#define OE_IS_ENABLED_MODULE_REPRESENTATIONS @IS_ENABLED_MODULE_REPRESENTATIONS@

#endif // OPTIONS_HPP
