cmake_minimum_required(VERSION 3.15.0)
project(openev-examples)
set(CMAKE_CXX_STANDARD 17)

file(GLOB EXAMPLE_FILES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)

foreach(EXAMPLE_FILE IN LISTS EXAMPLE_FILES)
  get_filename_component(EXAMPLE_NAME ${EXAMPLE_FILE} NAME_WE)
  openev_required_modules(${EXAMPLE_FILE} REQUIRED_MODULES MISSING_MODULES)
  if(MISSING_MODULES)
    message(STATUS "Example ${EXAMPLE_NAME} skipped, needs disabled module(s): ${MISSING_MODULES}")
  else()
    add_executable(${EXAMPLE_NAME} ${EXAMPLE_FILE})
    target_link_libraries(${EXAMPLE_NAME} openev)
  endif()
endforeach()
