name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
              sudo apt install libudev-dev
              sudo apt install libopencv-dev

      - name: Build
        run: |
              git clone https://github.com/raultapia/openev
              mkdir -p openev/build
              cd openev/build
              cmake ..
              make
              sudo make install

      - name: Build with no viz
        run: |
              cd openev/build
              sed -i 's/set(HAVE_VIZ 1)/set(HAVE_VIZ 0)/g' ../CMakeLists.txt
              cmake ..
              make
              sudo make install
