name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          sudo apt install libusb-1.0-0-dev
          sudo apt install libopencv-dev

      - name: Build
        run: |
              git clone https://github.com/raultapia/openev
              mkdir -p openev/build
              cd openev/build
              cmake ..
              make
              sudo make install
